version: '3.9'

services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: Klyukoyt
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  movie_service:
    restart: on-failure
    container_name: movie_service
    build: movie_service/
    ports:
      - "8000:80"
    depends_on:
      - database

  kinopoisk_service:
    restart: on-failure
    container_name: kinopoisk_service
    build: kinopoisk_service/
    ports:
      - "8001:80"
    depends_on:
      - database
